import React from 'react'

const contact = () => {
  return (
    <div>
        <h1>Contact Us</h1>
        <p>If you have any questions, feel free to reach out!</p>
    </div>
  )
}

export default contact

// Metadata for the contact page (SEO)
export const metadata = {
    title: "contact webD",
    description: "Generated by create next app",
};

